language: ruby
rbenv:
- 2.5.3
language: node_js
node_js:
- 10
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: MOVIE_DB_API_KEY
  app:
  run: rails db:migrate
